"""ProofCode version values.

APP_VERSION changes when ProofCode features change.
PROTOCOL_VERSION changes only when the Python ↔ TypeScript JSON contract changes.
"""

APP_VERSION = "0.12.0"
PROTOCOL_VERSION = "1"
BASELINE_SCHEMA_VERSION = "1"
CANDIDATE_EVIDENCE_SCHEMA_VERSION = "1"
DECISION_SCHEMA_VERSION = "2"
BENCHMARK_EVIDENCE_SCHEMA_VERSION = "1"
SANDBOX_EVIDENCE_SCHEMA_VERSION = "1"
